server:
  port: 8082
  servlet:
    context-path: /

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/spring-web
    username: root
    password: cfxzkX?i1


